name: duckstation-gpl
base: core24
version: '0.1-7371'
platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
summary: PlayStation Emulator
description: |
  DuckStation is an simulator/emulator of the Sony PlayStation(TM) console, focusing on playability, speed, and long-term maintainability. The goal is to be as accurate as possible while maintaining performance suitable for low-end devices.

  "Hack" options are discouraged, the default configuration should support all playable games with only some of the enhancements having compatibility issues.

  DuckStation features a fully-featured frontend built using Qt, as well as a fullscreen/TV UI based on Dear ImGui. Other features include

    Hardware renderer supporting OpenGL and Vulkan APIs.
    Upscaling, texture filtering, and true colour (24-bit) in hardware renderers.
    PGXP for geometry precision, texture correction, and depth buffer emulation.
    Accurate blending via Rasterizer Order Views/Fragment Shader Interlock.
    Texture replacement system in hardware renderers.
    Vectorized and multi-threaded software renderer.
    Motion adaptive deinterlacing.
    Adaptive downsampling filter.
    Screen rotation for vertical or "TATE" shmup games.
    Post processing shader chains (GLSL and Reshade FX).
    Border overlays/bezels displayed around game content.
    "Fast boot" for skipping BIOS splash/intro.
    Save state support, with runahead and rewind.
    Supports reading directly from CD, bin/cue images, raw bin/img files, MAME CHD, single-track ECM, MDS/MDF, and unencrypted PBP formats.
    Preloading of disc images to RAM to avoid disk sleeping hitches.
    Merging of multi-disc games in game list/grid with memory cards shared between discs.
    Automatic loading/applying of PPF patches.
    Direct booting of homebrew executables.
    Direct loading of Portable Sound Format (psf) files.
    Time stretched audio when running outside of 100% speed.
    Digital and analog controllers for input (rumble is forwarded to host).
    GunCon and Justifier lightgun support (simulated with mouse).
    NeGcon support.
    Controller presets and per-game configuration.
    Automatic content scanning - game titles/hashes are provided by redump.org.
    Optional automatic switching of memory cards for each game.
    Supports loading cheats from existing lists.
    Memory card editor and save importer.
    Emulated CPU overclocking.
    Integrated and remote debugging.
    Multitap controllers (up to 8 devices).
    RetroAchievements.
    Video capture with FFmpeg backends.
    Free camera function.
    Parallel port cartridge emulation.

  "PlayStation" and "PSX" are registered trademarks of Sony Interactive Entertainment Europe Limited. This project is not affiliated in any way with Sony Interactive Entertainment.
grade: stable
confinement: strict

apps:
  duckstation-gpl:
    command: usr/bin/duckstation-qt
    desktop: usr/share/applications/org.duckstation.DuckStation.desktop
    extensions:
      - gnome
    plugs:
      - home
      - removable-media
      - gtk-3-themes
      - icon-themes
      - desktop
      - desktop-legacy
      - x11
      - opengl
      - wayland
      - audio-playback
      - joystick
      - screen-inhibit-control
      - network

parts:
  duckstation-gpl:
    plugin: dump
    source: .
    build-packages:
      - wget
    override-build: |
      craftctl default
      pwd
      ls -l
      wget https://github.com/Kyuyrii/Duckstation-GPL3/releases/download/v0.1-7371/DuckStation-x64.AppImage
      chmod +x DuckStation-x64.AppImage
      ./DuckStation-x64.AppImage --appimage-extract
      mkdir -p $CRAFT_PART_INSTALL/
      sed -i 's|Icon=org.duckstation.DuckStation|Icon=${SNAP}/usr/share/icons/hicolor/512x512/apps/org.duckstation.DuckStation.png|' squashfs-root/usr/share/applications/org.duckstation.DuckStation.desktop
      sed -i 's|Exec=duckstation-qt %f|Exec=${SNAP}/usr/bin/duckstation-qt %f|' squashfs-root/usr/share/applications/org.duckstation.DuckStation.desktop
      sed -i 's|TryExec=duckstation-qt|TryExec=${SNAP}/usr/bin/duckstation-qt|' squashfs-root/usr/share/applications/org.duckstation.DuckStation.desktop
      mv -f squashfs-root/usr $CRAFT_PART_INSTALL/
    prime:
      - usr
